### ISSUE TITLE
Feature: Use symbols that represents statuses to accompany color for colorblind individuals

### ISSUE THREAD

**Issue by somewhatabstract** [AlonAm/AnyStatus#17]
### Installed product versions
- Visual Studio: 2015 Enterprise Update 3
- AnyStatus: 1.0 in about but I think it's 0.8
### Description

I work with some colorblind individuals who would love this extension if it didn't solely rely on color swatches for conveying state. It would be very useful if they could edit the swatch colors, and even more useful if symbols were used alongside the colors to convey pass/fail state (possibly optional).
### Current behavior

Not colorblind friendly interface
### Expected behavior

Colorblind friendly interface

**Comment by somewhatabstract** [comment]
Just realised this is probably a duplicate of #13

**Comment by AlonAm** [comment]
it's not a duplicate because #13 purpose is to represent the different types of monitors (http, build, tcp, etc.) with icons to quickly understand what is failing.

allowing the users to customize the status colors is a good idea, I'll add it to the roadmap.

about representing the state with an icon...let me think about it...i kinda like it minimal

**Comment by somewhatabstract** [comment]
It can easily be optional. Also, seems like it would be a great way to create a minimal dashboard layout where the labels are gone and tooltips tell you which monitor is which. People would easily remember where they put certain monitors in their dash.

**Comment by AlonAm** [comment]
allowing to show/hide the labels is interesting...
the thing with the icons is that there are different types of monitors and the context might be different.
for example a closed GitHub Issue is colored Red (like on GitHub itself) which is not a failure...

**Comment by somewhatabstract** [comment]
I think it's the same with color. Right now, red is used when a long fails
but I might want the failure to be a good thing.

Being able to map results to a status indication, whether color or symbol
is an additional issue.

**Comment by AlonAm** [comment]
btw, are you using the Dark or Blue theme?
which theme do color-blinded ppl use?

**Comment by somewhatabstract** [comment]
@scottfavre can you chime in here?

**Comment by scottfavre** [comment]
Any color mapping is going to fail for some set of users. For me the red/green are difficult to distinguish.

Looks like at least there are a green = ok, red = error, blue = ???.

Adding a checkmark icon for OK and an X or 🚫for error would be good. Not sure what blue means, but maybe a question mark or something similar.

Note that it would be just fine to make the icons optional, as long as it is easily discovered.

**Comment by AlonAm** [comment]
thanks a lot for your feedback.
blue means the build is in progress (running).

I've added those features to the roadmap.
in general it means adding State to the monitors, which makes sense, and enable the user to customize State color.

**Comment by scottfavre** [comment]
Thanks! I always appreciate it when projects accommodate users with color-sight deficiencies.

**Comment by AlonAm** [comment]
In your opinion, what is the right layout for the status bar?
where "Stats" is a textual summary of items within a group (for example: "1 failed, 1 running")

for example: 
__________________________________
| Color box | Label | Icon | Stats |
|_________________________________|

or 
__________________________________
| Color box | Icon | Label | Stats |
|_________________________________|

**Comment by somewhatabstract** [comment]
Icon first, for me. I'll defer to @scottfavre though.

**Comment by AlonAm** [comment]
Created a new feature request specific to the color customization: #23 
While this request is specific to icons

**Comment by scottfavre** [comment]
Icon first would be better, I think.

**Comment by AlonAm** [comment]
As a mid-way solution, till the color customization and status icons features be ready
I've added tooltips that describe the status and type of monitors.
Released in v0.9.10 now on VS gallery.

In addition, here's a list of status codes and colors: https://github.com/AlonAm/AnyStatus/wiki/Status-Color-Table

**Comment by AlonAm** [comment]
here's a little sneak peek, still looking for the right icons.

![image](https://cloud.githubusercontent.com/assets/3127610/20096682/baf71ab0-a5b3-11e6-8598-c78dd0123727.png)

**Comment by AlonAm** [comment]
here's a full list of icons: http://glyphlist.azurewebsites.net/knownmonikers/

**Comment by AlonAm** [comment]
Another example:

![image](https://cloud.githubusercontent.com/assets/3127610/20100045/31ff243a-a5c4-11e6-84c1-840c57769c77.png)

**Comment by scottfavre** [comment]
Like how it looks.

**Comment by AlonAm** [comment]
I have added the status icons in v0.9.12 as requested. Currently, it is disabled by default.

In addition, I have added 2 checkboxes to the options page to enable users show/hide the status icons and/or colors.

CI build is available at http://vsixgallery.com/extension/AnyStatus.VSPackage.6f25620d-ff50-42d1-89da-709a45cebe10/

Please let me know what you think and whether you experience any issues.

Thanks

![image](https://cloud.githubusercontent.com/assets/3127610/20133752/7825f2b0-a671-11e6-933b-944acbed747a.png)

**Comment by AlonAm** [comment]
Dark theme example:

![image](https://cloud.githubusercontent.com/assets/3127610/20134568/887f6fc6-a674-11e6-90f7-6d22868ca843.png)

**Comment by AlonAm** [comment]
released to VS Gallery in v0.9.17

@somewhatabstract @scottfavre thanks a lot for your feedback and feature suggestion. please let me know if there are further changes you'd like (pull requests are appreciated as well).

**Comment by somewhatabstract** [comment]
![image](https://cloud.githubusercontent.com/assets/1266297/20194441/f9be3c9c-a757-11e6-935d-415333c25c27.png)

It's working great although the icons look a little fuzzy on my screen. I have a high DPI setting so that may be the cause. Might be worth shifting to vector graphics for the icons. Checkout [Metro Studio](https://www.syncfusion.com/downloads/metrostudio) from Syncfusion; it's free and can provide XAML for the icons.

**Comment by AlonAm** [comment]
i see.
i'm close to enabling color customization.
once I complete that i'll see what i can do about the high dpi support.
it's either using the built in VS tools for that or shifting to vector graphics.
thanks for the metro studio link.

**Comment by AlonAm** [comment]
@somewhatabstract I have replaced the png icons with vector graphics in v0.10.15
please let me know if the icons looks better now on high DPI. thanks!

**Comment by somewhatabstract** [comment]
Much better: 

![image](https://cloud.githubusercontent.com/assets/1266297/20495585/5630109e-afe7-11e6-82a1-114369cb4513.png)
