### ISSUE TITLE
Feature: Refresh all monitors within a group

### ISSUE THREAD

**Issue by somewhatabstract** [AlonAm/AnyStatus#18]
### Installed product versions
- Visual Studio: 2015 Enterprise Update 3
- AnyStatus: 1.0 in about but I think it's 0.8
### Description

I want to be able to refresh or disable an entire group rather than each item individually or all monitors at once.
### Current behavior

Cannot refresh or disable groups, only items (refresh or disable) or everything (refresh only)
### Expected behavior

Can refresh and disable groups in addition to all monitors and individual ones

**Comment by AlonAm** [comment]
good idea

**Comment by AlonAm** [comment]
moved Disable/Enable all items within a group to #20

**Comment by AlonAm** [comment]
added a refresh button to both group and tree-view context menu.
refreshing a specific group will refresh only the items within that group.

**Comment by AlonAm** [comment]
released in 0.9.1 now on Visual Studio Gallery
