### ISSUE TITLE
Feature: Duplicate existing item

### ISSUE THREAD

**Issue by somewhatabstract** [AlonAm/AnyStatus#19]
### Description

I have several appveyor projects on the same account. Rather than having to enter each item's properties every time, it would be really useful if I could just duplicate an existing monitor and then edit its properties. This would also be useful for groups, although less important.
### Current behavior

Can only add folder or item, and drag drop to change hierarchy and order.
### Expected behavior

Can duplicate folders and items via right click option, and possible Ctrl+V,Ctrl+C, and Ctrl+DragDrop

**Comment by AlonAm** [comment]
Hi :-)
thanks for your feedback and requests. i'll review your requests and get back to ya asap.

**Comment by AlonAm** [comment]
that should be fairly easy to provide. i'll take care of it asap, hopefully during the next week or two.
thank you for your feedback!

**Comment by AlonAm** [comment]
added Duplicate menu item to the context menu.
released in 0.9.2
copy-paste functionlaity will be implemented  separately.
thanks a lot for the feature suggestion.
