### ISSUE TITLE
Feature: Status colors customization

### ISSUE THREAD

**Issue by AlonAm** [AlonAm/AnyStatus#23]
### Current behavior
The user cannot customize the status colors

### Expected behavior
The user can customize status colors in Options page

**Comment by midiway** [comment]
VERY NICE EXTENSION
Yep, the color is really an issue for me, I am a bit color blind, so I cant distinguish red from green.. a black for an error status would be better, but customization would be much better
What does the blue color represents?

**Comment by AlonAm** [comment]
The blue color represents an In Progress (Running) build.
Here's a list of colors and statuses: https://github.com/AlonAm/AnyStatus/wiki/Status-Color-Table
Color customization is on the roadmap and will be delivered soon I hope.
As a mid-way solution, I added tooltips that describe the status and type of the monitors.
It was released in version 0.9.10 and available on VS Gallery.

Thank you for your feedback.

**Comment by AlonAm** [comment]
here's how it looks like so far

![image](https://cloud.githubusercontent.com/assets/3127610/20212339/49384a20-a80b-11e6-97e5-0b147cd90121.png)

suggestions?

**Comment by scottfavre** [comment]
Looks pretty good!

Minor suggestion that may end up being a lot of work: instead of text boxes for priority, have an ordered list with a means of rearranging the order (drag-and-drop, move-up/move-down buttons, etc.).

Also, is the highest priority status displayed, or the lowest? I would expect error and running to be on opposite ends of that scale.

**Comment by midiway** [comment]
well, it is good, you already know it, just don't lose time with it :smile:

**Comment by AlonAm** [comment]
Thanks, I'll remove Priority for now and release just the color customization soon

**Comment by AlonAm** [comment]
Released in v0.10.15 now on VS Gallery.

@midiway @somewhatabstract @scottfavre I've included a lot of changes and refactoring, please let me know if you experience any issues after installing the new version.

**Comment by midiway** [comment]
sure, gonna give a try
