### ISSUE TITLE
Suggestion: Add an icon for *New Item' and *New Folder* in the tool window's toolbar

### ISSUE THREAD

**Issue by yannduran** [AlonAm/AnyStatus#34]
It took me a while to figure out that I needed to right-click ti be able to add a new item.

**Comment by AlonAm** [comment]
There are two options here,
One is to add buttons to the toolbar.
Two is to display a message where you right-clicked with links to create a new item or folder. The message will be shown only when the treeview is empty.

Either way, it's important to help new users get started.
Thank You

**Comment by AlonAm** [comment]
released in v0.10.84

**Comment by yannduran** [comment]
That looks great Alon. It's exactly what a new user would expect to see.

Thank you!
