### ISSUE TITLE
Unable to 'Add a New Item' Anymore (v0.11.16)

### ISSUE THREAD

**Issue by yannduran** [AlonAm/AnyStatus#37]
### Installed product versions
- **Visual Studio:**
   - *VS 2015 Community*
   - *Version 14.0.25431.01 Update 3*
- **AnyStatus:**
   - *Version: 0.11.16*

### Description
Clicking the add item button throws up an error DialogBox

>![devenv_2016-12-28_01-22-58](https://cloud.githubusercontent.com/assets/2031126/21501724/684ebfae-cc9e-11e6-853d-e8bea191526a.png)

Right-clicking and selecting 'add item', nothing happens at all

### Steps to recreate
1. Try to add an item (either way)

### Current behavior
An error DialogBox appears, or just nothing happens

### Expected behavior
It should open the correct DialogBox to be able to display or edit the status details

**Comment by AlonAm** [comment]
Thanks for reporting, I'm on it

**Comment by AlonAm** [comment]
Is there an error message in the vs output window?

**Comment by AlonAm** [comment]
Did you install version 0.11.16 by downloading it from the website or by using Visual Studio "Extensions and Updates" window?

**Comment by AlonAm** [comment]
I was unable to reproduce this issue with version 0.11.18, can you please update and try again?
If the issue persists, please check for error messages in Visual Studio output window

**Comment by yannduran** [comment]
It seems to be working fine now, thanks for the quick response!

**Comment by AlonAm** [comment]
Excellent, thank you for reporting this issue.
